import React, { useState } from 'react';
import { Cloud, Server, Database, Code, HardDrive, Zap, Router, Plus, Trash2 } from 'lucide-react';

// Bibliothek verfügbarer Cloud-Bausteine mitsamt ihrem Terraform (HCL) Snippet.
// Jede Komponente, die auf die Canvas gezogen wird, trägt ihren eigenen
// Ressourcen-Block bei, sodass main.tf immer den aktuellen Architektur-Stand widerspiegelt.
const COMPONENT_LIBRARY = [
  {
    type: 'network', name: 'AWS VPC (Virtual Private Cloud)',
    terraform: () => `resource "aws_vpc" "main" {\n  cidr_block = "10.0.0.0/16"\n  tags = { Name = "DevGame-VPC" }\n}`
  },
  {
    type: 'compute', name: 'EC2 Compute Node (App)',
    terraform: () => `resource "aws_instance" "app_server" {\n  ami           = "ami-0c55b159cbfafe1f0"\n  instance_type = "t3.micro"\n  subnet_id     = aws_vpc.main.id\n}`
  },
  {
    type: 'database', name: 'RDS PostgreSQL Database',
    terraform: () => `resource "aws_db_instance" "database" {\n  allocated_storage    = 20\n  engine               = "postgres"\n  instance_class       = "db.t3.micro"\n  username             = "admin"\n  password             = "SecurePassword123!"\n}`
  },
  {
    type: 'storage', name: 'S3 Object Storage Bucket',
    terraform: () => `resource "aws_s3_bucket" "assets" {\n  bucket = "devgame-app-assets"\n}`
  },
  {
    type: 'serverless', name: 'Lambda Function (Serverless)',
    terraform: () => `resource "aws_lambda_function" "worker" {\n  function_name = "devgame-worker"\n  runtime       = "nodejs20.x"\n  handler       = "index.handler"\n  filename      = "worker.zip"\n}`
  },
  {
    type: 'network', name: 'Application Load Balancer',
    terraform: () => `resource "aws_lb" "app_alb" {\n  name               = "devgame-alb"\n  load_balancer_type = "application"\n  subnets            = [aws_vpc.main.id]\n}`
  }
];

const ICONS_BY_TYPE = {
  network: Router,
  compute: Server,
  database: Database,
  storage: HardDrive,
  serverless: Zap
};

const COLORS_BY_TYPE = {
  network: '#a855f7',
  compute: '#38bdf8',
  database: '#10b981',
  storage: '#f59e0b',
  serverless: '#f472b6'
};

let nextComponentId = 4;

export default function CloudDesignerLab({ onRewardXP }) {
  const [components, setComponents] = useState([
    { id: 'vpc', name: 'AWS VPC (Virtual Private Cloud)', type: 'network' },
    { id: 'ec2', name: 'EC2 Compute Node (App)', type: 'compute' },
    { id: 'rds', name: 'RDS PostgreSQL Database', type: 'database' }
  ]);

  const [generatedTerraform, setGeneratedTerraform] = useState('');

  const handleAddComponent = (libraryItem) => {
    setComponents(prev => [
      ...prev,
      { id: `custom-${nextComponentId++}`, name: libraryItem.name, type: libraryItem.type }
    ]);
    setGeneratedTerraform('');
  };

  const handleRemoveComponent = (id) => {
    setComponents(prev => prev.filter(c => c.id !== id));
    setGeneratedTerraform('');
  };

  const generateTerraformCode = () => {
    const resourceBlocks = components
      .map(comp => {
        const libraryMatch = COMPONENT_LIBRARY.find(l => l.name === comp.name);
        return libraryMatch ? libraryMatch.terraform() : null;
      })
      .filter(Boolean)
      .join('\n\n');

    const tf = `# Terraform Cloud Infrastructure Architecture (Generated by IT-DevGame)
provider "aws" {
  region = "eu-central-1"
}

${resourceBlocks}`;
    setGeneratedTerraform(tf);
    if (onRewardXP) onRewardXP(30);
  };

  return (
    <div style={{ background: 'var(--bg-card)', padding: '28px', borderRadius: 'var(--radius-xl)', border: '1px solid var(--border-color)' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '24px', flexWrap: 'wrap', gap: '16px' }}>
        <div>
          <span className="badge badge-indigo" style={{ marginBottom: '8px' }}>
            <Cloud size={14} /> Cloud Native & DevOps (AWS / IaC)
          </span>
          <h2 style={{ fontSize: '1.8rem', fontWeight: '800', margin: '4px 0', color: 'var(--text-main)' }}>
            ☁️ Cloud Infrastructure & Terraform IaC Designer
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem' }}>
            Designe Cloud-Architekturen und generiere echten Terraform Code (Infrastructure as Code).
          </p>
        </div>
      </div>

      {/* Cloud Components Canvas */}
      <div style={{ background: '#0f172a', padding: '32px', borderRadius: 'var(--radius-lg)', marginBottom: '16px', display: 'flex', gap: '20px', flexWrap: 'wrap' }}>
        {components.length === 0 && (
          <span style={{ color: '#64748b', fontSize: '0.9rem' }}>
            Keine Komponenten auf der Canvas. Füge unten eine hinzu.
          </span>
        )}
        {components.map((comp) => {
          const Icon = ICONS_BY_TYPE[comp.type] || Cloud;
          const color = COLORS_BY_TYPE[comp.type] || '#38bdf8';
          return (
            <div key={comp.id} style={{ background: '#1e293b', border: `2px solid ${color}`, padding: '20px', borderRadius: '12px', minWidth: '220px', position: 'relative' }}>
              <button
                onClick={() => handleRemoveComponent(comp.id)}
                title="Komponente entfernen"
                style={{ position: 'absolute', top: '10px', right: '10px', background: 'none', border: 'none', cursor: 'pointer', color: '#64748b' }}
              >
                <Trash2 size={16} />
              </button>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px' }}>
                <Icon color={color} />
                <span style={{ color: '#fff', fontWeight: '700' }}>{comp.name}</span>
              </div>
              <span className="badge badge-indigo" style={{ fontSize: '0.75rem' }}>{comp.type.toUpperCase()}</span>
            </div>
          );
        })}
      </div>

      {/* Komponenten-Bibliothek zum Hinzufügen */}
      <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap', marginBottom: '24px' }}>
        {COMPONENT_LIBRARY.map((item) => (
          <button
            key={item.name}
            onClick={() => handleAddComponent(item)}
            className="btn btn-secondary"
            style={{ fontSize: '0.8rem', padding: '8px 12px' }}
          >
            <Plus size={14} /> {item.name.split('(')[0].trim()}
          </button>
        ))}
      </div>

      <div style={{ display: 'flex', gap: '16px', marginBottom: '24px' }}>
        <button className="btn btn-primary" onClick={generateTerraformCode} disabled={components.length === 0}>
          <Code size={16} /> Terraform Code (main.tf) Generieren
        </button>
      </div>

      {generatedTerraform && (
        <div className="code-window">
          <div className="code-header" style={{ background: '#1e293b', padding: '12px 16px', color: '#38bdf8' }}>
            <span>main.tf (HCL HashiCorp Language)</span>
          </div>
          <pre style={{ background: '#090d16', color: '#38bdf8', padding: '16px', borderRadius: '0 0 var(--radius-lg) var(--radius-lg)', margin: 0, overflowX: 'auto', fontFamily: 'monospace' }}>
            {generatedTerraform}
          </pre>
        </div>
      )}
    </div>
  );
}
